### ISSUE TITLE
Duplicate key error on mongo.

### ISSUE THREAD

**Issue by illegalprime** [HackGT/registration#172]
When signing up on `/auth/signup` I get this:
```
MongoError: E11000 duplicate key error collection: registration-dev.users index: username_1 dup key: { : null }
    at Function.MongoError.create (/home/michael/cde/hackgt/registration/node_modules/mongoose/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/home/michael/cde/hackgt/registration/node_modules/mongoose/node_modules/mongodb/lib/utils.js:139:22)
    at /home/michael/cde/hackgt/registration/node_modules/mongoose/node_modules/mongodb/lib/collection.js:669:23
    at handleCallback (/home/michael/cde/hackgt/registration/node_modules/mongoose/node_modules/mongodb/lib/utils.js:120:56)
    at /home/michael/cde/hackgt/registration/node_modules/mongoose/node_modules/mongodb/lib/bulk/unordered.js:465:9
    at handleCallback (/home/michael/cde/hackgt/registration/node_modules/mongoose/node_modules/mongodb/lib/utils.js:120:56)
    at resultHandler (/home/michael/cde/hackgt/registration/node_modules/mongoose/node_modules/mongodb/lib/bulk/unordered.js:413:5)
    at /home/michael/cde/hackgt/registration/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickDomainCallback (internal/process/next_tick.js:198:9)
```

**Comment by illegalprime** [comment]
Can't reproduce anymore, closing.
