### ISSUE TITLE
GitHub login user validation failed

### ISSUE THREAD

**Issue by as1216** [HackGT/registration#54]
Comes out as a plain text MongooseError...user should be able to log in again

```
MongooseError: User validation failed
    at ValidationError (/usr/src/checkin/node_modules/mongoose/lib/error/validation.js:23:11)
    at model.Document.invalidate (/usr/src/checkin/node_modules/mongoose/lib/document.js:1535:32)
    at /usr/src/checkin/node_modules/mongoose/lib/document.js:1410:17
    at validate (/usr/src/checkin/node_modules/mongoose/lib/schematype.js:707:7)
    at /usr/src/checkin/node_modules/mongoose/lib/schematype.js:752:11
    at Array.forEach (native)
    at SchemaString.SchemaType.doValidate (/usr/src/checkin/node_modules/mongoose/lib/schematype.js:712:19)
    at /usr/src/checkin/node_modules/mongoose/lib/document.js:1408:9
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by petschekr** [comment]
Could you provide some more information about what you were doing at the time that you encountered this error? I'm not able to reproduce this locally at the moment.

**Comment by petschekr** [comment]
@as1216

**Comment by kexin-zhang** [comment]
also got this error when trying to authenticate with Github.

![image](https://cloud.githubusercontent.com/assets/17093911/24591580/c9d6a2da-17d2-11e7-9df8-56d5256eaefa.png)

**Comment by as1216** [comment]
Here are some steps to replicate this issue (and exactly what I did):
1) log in with your github account connected to HackGT (me: as1216)
2) enter the wrong password (fake pass: garbage)
3) press the enter keyboard*
*Maybe this is a "click the Login button and it works" issue? Couldn't re-test it again.

It just takes you to the mongoose error directly without any way of re-entering my password.

**Comment by petschekr** [comment]
This is caused by not having a public email on your GitHub profile. Working on a fix right now.
